/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { Controls, useControl } from 'react-three-gui';

export default function Model(props) {
	const rotationX = useControl('Rotation X', { type: 'number' });
	const posX = useControl('Pos X', { type: 'number' });
	const scaleX = useControl('Scale X', { type: 'number' });
	const scaleY = useControl('Scale Y', { type: 'number' });

	const group = useRef();
	const { nodes, materials } = useLoader(GLTFLoader, '/Assembly2.gltf');
	return (
		<group
			ref={group}
			{...props}
			dispose={null}
			rotation-x={rotationX}
			position-x={posX}
			scale-x={scaleX}
			scale-y={scaleY}
		>
			<mesh
				material={nodes.Solid1.material}
				geometry={nodes.Solid1.geometry}
			/>
			<mesh
				material={nodes.Solid2.material}
				geometry={nodes.Solid2.geometry}
			/>
			<mesh
				material={nodes.Solid3.material}
				geometry={nodes.Solid3.geometry}
			/>
			<mesh
				material={nodes.Solid4.material}
				geometry={nodes.Solid4.geometry}
			/>
			<mesh
				material={nodes.Solid5.material}
				geometry={nodes.Solid5.geometry}
			/>
			<mesh
				material={nodes.Solid11.material}
				geometry={nodes.Solid11.geometry}
			/>
			<mesh
				material={nodes.Solid12.material}
				geometry={nodes.Solid12.geometry}
			/>
			<mesh
				material={nodes.Solid13.material}
				geometry={nodes.Solid13.geometry}
			/>
			<mesh
				material={nodes.Solid21.material}
				geometry={nodes.Solid21.geometry}
			/>
			<mesh
				material={nodes.Solid31.material}
				geometry={nodes.Solid31.geometry}
			/>
			<mesh
				material={nodes.Solid41.material}
				geometry={nodes.Solid41.geometry}
			/>
			<mesh
				material={nodes.Solid51.material}
				geometry={nodes.Solid51.geometry}
			/>
			<mesh
				material={nodes.Solid14.material}
				geometry={nodes.Solid14.geometry}
			/>
			<mesh
				material={nodes.Solid15.material}
				geometry={nodes.Solid15.geometry}
			/>
			<mesh
				material={nodes.Solid16.material}
				geometry={nodes.Solid16.geometry}
			/>
			<mesh
				material={nodes.Solid17.material}
				geometry={nodes.Solid17.geometry}
			/>
			<mesh
				material={nodes.Solid18.material}
				geometry={nodes.Solid18.geometry}
			/>
			<mesh
				material={nodes.Solid22.material}
				geometry={nodes.Solid22.geometry}
			/>
			<mesh
				material={nodes.Solid32.material}
				geometry={nodes.Solid32.geometry}
			/>
			<mesh
				material={nodes.Solid42.material}
				geometry={nodes.Solid42.geometry}
			/>
			<mesh
				material={nodes.Solid52.material}
				geometry={nodes.Solid52.geometry}
			/>
			<mesh
				material={nodes.Solid19.material}
				geometry={nodes.Solid19.geometry}
			/>
			<mesh
				material={nodes.Solid110.material}
				geometry={nodes.Solid110.geometry}
			/>
			<mesh
				material={nodes.Solid111.material}
				geometry={nodes.Solid111.geometry}
			/>
			<mesh
				material={nodes.Solid112.material}
				geometry={nodes.Solid112.geometry}
			/>
			<mesh
				material={nodes.Solid113.material}
				geometry={nodes.Solid113.geometry}
			/>
		</group>
	);
}
