/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

export default function Model(props) {
	const group = useRef();
	const { nodes, materials } = useLoader(GLTFLoader, '/BasicTable.gltf');
	return (
		<group ref={group} {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group
					rotation={[Math.PI / 2, 0, 0]}
					scale={[0.01, 0.01, 0.01]}
				>
					<mesh
						material={materials['3D Oak - Semigloss']}
						geometry={nodes.mesh_0.geometry}
					/>
					<mesh
						material={materials['Powder Coat (Black)']}
						geometry={nodes.mesh_1.geometry}
					/>
					<mesh
						material={materials['Powder Coat (Black)']}
						geometry={nodes.mesh_2.geometry}
					/>
					<mesh
						material={materials['Powder Coat (Black)']}
						geometry={nodes.mesh_3.geometry}
					/>
					<mesh
						material={materials['Powder Coat (Black)']}
						geometry={nodes.mesh_4.geometry}
					/>
					<mesh
						material={materials['Powder Coat (Black)']}
						geometry={nodes.mesh_5.geometry}
					/>
					<mesh
						material={materials['Powder Coat (Black)']}
						geometry={nodes.mesh_6.geometry}
					/>
				</group>
			</group>
		</group>
	);
}
