/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { useControl } from 'react-three-gui';

export default function Model(props) {
	const scaleX = useControl('Scale X', { type: 'number' });
	const rotationX = useControl('Rotation X', { type: 'number' });
	const posX = useControl('Pos X', { type: 'number' });
	const { position } = props;
	const group = useRef();
	const { nodes, materials } = useLoader(GLTFLoader, '/BasicShelf.gltf');
	console.log(nodes);
	return (
		<group
			ref={group}
			{...props}
			dispose={null}
			// position={position}
			visible={true}
			scale-x={scaleX * 1000}
			rotation-x={rotationX}
			position-x={posX * 1000}
		>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group
					rotation={[Math.PI / 2, 0, 0]}
					scale={[0.01, 0.01, 0.01]}
				>
					<mesh
						// material={materials['Panel Beige']}
						geometry={nodes.mesh_0.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_1.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_2.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_3.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_4.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_5.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_6.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_7.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_8.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_9.geometry}
					/>
					<group position={[0, 0, -29.64]}>
						<mesh
							material={materials['Panel Beige']}
							geometry={nodes.mesh_10.geometry}
						/>
					</group>
					<group position={[0, 0, -59.28]}>
						<mesh
							material={materials['Panel Beige']}
							geometry={nodes.mesh_11.geometry}
						/>
					</group>
					<group position={[0, 0, -88.92]}>
						<mesh
							material={materials['Panel Beige']}
							geometry={nodes.mesh_12.geometry}
						/>
					</group>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_13.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_14.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_15.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_16.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_17.geometry}
					/>
					<group position={[0, 0, -0.36]} rotation={[0, 0, 0]}>
						<mesh
							material={materials['Panel Beige']}
							geometry={nodes.mesh_18.geometry}
						/>
					</group>
					<group position={[0, 0, -4.64]} rotation={[0, 0, 0]}>
						<mesh
							material={materials['Panel Beige']}
							geometry={nodes.mesh_19.geometry}
						/>
					</group>
					<group position={[0, 0, 11.08]} rotation={[0, 0, 0]}>
						<mesh
							material={materials['Panel Beige']}
							geometry={nodes.mesh_20.geometry}
						/>
					</group>
					<group position={[0, 0, 0.72]} rotation={[0, 0, 0]}>
						<mesh
							material={materials['Panel Beige']}
							geometry={nodes.mesh_21.geometry}
						/>
					</group>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_22.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_23.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_24.geometry}
					/>
					<mesh
						material={materials['Panel Beige']}
						geometry={nodes.mesh_25.geometry}
					/>
				</group>
			</group>
		</group>
	);
}
