/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/Bookshelf.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Panel_Beige} geometry={nodes.Body1.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body2.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body3.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body4.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body5.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body11.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body12.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body13.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body21.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body31.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body41.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body51.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body14.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body15.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body16.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body17.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body18.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body22.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body32.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body42.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body52.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body19.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body110.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body111.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body112.geometry} />
      <mesh material={materials.Panel_Beige} geometry={nodes.Body113.geometry} />
    </group>
  )
}
