/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, useState } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { useStore } from './zusStore';
import { Controls, useControl } from 'react-three-gui';

export default function DrawerModel(props) {
	// const rotationX = useControl('Rotation X', { type: 'number' });
	// const posX = useControl('Pos X', { type: 'number' });
	// const scaleX = useControl('Scale X', { type: 'number' });
	const group = useRef();
	const { position } = props;
	const [clicked, setClicked] = useState(false);

	const { nodes, materials } = useLoader(GLTFLoader, '/drawer.gltf');
	// console.log(props);

	return (
		<group
			ref={group}
			{...props}
			dispose={null}
			position={props.position}
			visible={!clicked}
			onClick={(e) => setClicked(!clicked)}
			// rotation-x={rotationX}
			// position-x={posX * 100}
			// scale-x={scaleX}
		>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid1.geometry}
				// position={(0, 0, 0)}
			>
				<meshStandardMaterial attach="material" color="hotpink" />
			</mesh>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid2.geometry}
				// scale-x={scaleX}
				// position-x={posX * 1000}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid3.geometry}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid4.geometry}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid5.geometry}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid6.geometry}
			>
				<meshStandardMaterial attach="material" color="teal">
					{/* {console.log('Hello', nodes.Solid1.position)}
					{nodes.Solid1.position.set(1000, 2, 3)} */}
				</meshStandardMaterial>
			</mesh>
		</group>
	);
}
