/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, useEffect, useState } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { useSnapshot } from 'valtio';
import store from './store';
import { Controls, useControl, withControls } from 'react-three-gui';
import { MeshBasicMaterial, MeshStandardMaterial } from 'three';
const getNames = (nodes) => {
	// the below function works perfectly except triggers too many re-renders for some reason.
	Object.entries(nodes).map((i) => {
		const name = i[0];
		store.modelFactors[name] = nodes[name].geometry.boundingBox.getSize();
	});
};

export default function Model(props) {
	console.log('component Mount');
	const snap = useSnapshot(store);
	const group = useRef();

	const { nodes, materials } = useLoader(GLTFLoader, '/SolidTabe.gltf');
	const [cover, setCover] = useState(false);

	const legMaterial = new MeshStandardMaterial({ color: 'black' });
	const cupMaterial = new MeshStandardMaterial({ color: 'grey' });
	const {
		getPos,
		getScaleWithOffset,
		getScale,
		getEdge,
		getPosOffset,
	} = snap.functions;
	const { scale, borderScale } = snap.transforms;
	const {
		topper,
		legs,
		table,
		TopSetF2: { z: borderWidth },
		TopSetF2,
		TopSetL2,
		LegFL,
		InnerF,
		InnerL,
		cups,
	} = snap.modelFactors;

	useEffect(() => {
		// getNames(nodes);
		// group.current.castShadow = true;
		// group.current.receiveShadow = true;
	}, []);

	useEffect(() => {}, [snap.transforms]);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name={'Front'}>
				<group
					name={'Front Scale'}
					position-z={-getPos(table.z, scale.z)}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						position-z={-getEdge(table.z, borderScale)}
						scale-x={getScaleWithOffset(
							table.x,
							borderWidth,
							borderScale,
							scale.x
						)}
						scale-z={borderScale}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetF2.geometry}
					/>
					<mesh
						position-z={-getEdge(table.z, borderScale)}
						scale-x={getScaleWithOffset(
							table.x,
							borderWidth,
							borderScale,
							scale.x
						)}
						scale-z={borderScale}
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovF2.geometry}
					/>
					<mesh
						position-z={getPosOffset(borderWidth, borderScale)}
						scale-x={getScaleWithOffset(
							table.x,
							borderWidth,
							borderScale,
							scale.x
						)}
						material={materials.Panel_Beige}
						geometry={nodes.InnerF.geometry}
					/>
					<mesh
						scale-x={getScaleWithOffset(
							table.x,
							LegFL.x,
							1,
							scale.x
						)}
						material={materials.Panel_Beige}
						geometry={nodes.RailF.geometry}
					/>
				</group>
			</group>
			<group name={'Back'}>
				<group
					name={'Back Scale'}
					position-z={getPos(table.z, scale.z)}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						scale-x={getScaleWithOffset(
							table.x,
							borderWidth,
							borderScale,
							scale.x
						)}
						position-z={getEdge(table.z, borderScale)}
						scale-z={borderScale}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetB2.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						position-z={getEdge(table.z, borderScale)}
						scale-z={borderScale}
						scale-x={getScaleWithOffset(
							table.x,
							borderWidth,
							borderScale,
							scale.x
						)}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovB2.geometry}
					/>
					<mesh
						scale-x={getScaleWithOffset(
							table.x,
							borderWidth,
							borderScale,
							scale.x
						)}
						position-z={-getPosOffset(borderWidth, borderScale)}
						material={materials.Panel_Beige}
						geometry={nodes.InnerB.geometry}
					/>
					<mesh
						scale-x={getScaleWithOffset(
							table.x,
							LegFL.x,
							1,
							scale.x
						)}
						material={materials.Panel_Beige}
						geometry={nodes.RailB.geometry}
					/>
				</group>
			</group>
			<group name={'Right'}>
				<group
					name={'Right Scale'}
					position-x={-getPos(table.x, scale.x)}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						position-x={-getEdge(table.x, borderScale)}
						scale-x={borderScale}
						scale-z={getScaleWithOffset(
							table.z,
							borderWidth,
							borderScale,
							scale.z
						)}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetR2.geometry}
					/>
					<mesh
						position-x={getPosOffset(borderWidth, borderScale)}
						scale-z={getScaleWithOffset(
							table.z,
							borderWidth,
							borderScale,
							scale.z
						)}
						material={materials.Panel_Beige}
						geometry={nodes.InnerR.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						position-x={-getEdge(table.x, borderScale)}
						scale-x={borderScale}
						scale-z={getScaleWithOffset(
							table.z,
							borderWidth,
							borderScale,
							scale.z
						)}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovR2.geometry}
					/>
					<mesh
						scale-z={getScaleWithOffset(
							table.z,
							LegFL.z,
							1,
							scale.z
						)}
						material={materials.Panel_Beige}
						geometry={nodes.RailR.geometry}
					/>
				</group>
			</group>
			<group name={'Left'}>
				<group
					name={'Left Scale'}
					position-x={getPos(table.x, scale.x)}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						position-x={getEdge(table.x, borderScale)}
						scale-x={borderScale}
						scale-z={getScaleWithOffset(
							table.z,
							borderWidth,
							borderScale,
							scale.z
						)}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetL2.geometry}
					/>
					<mesh
						position-x={-getPosOffset(borderWidth, borderScale)}
						scale-z={getScaleWithOffset(
							table.z,
							borderWidth,
							borderScale,
							scale.z
						)}
						material={materials.Panel_Beige}
						geometry={nodes.InnerL.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						position-x={getEdge(table.x, borderScale)}
						scale-x={borderScale}
						scale-z={getScaleWithOffset(
							table.z,
							borderWidth,
							borderScale,
							scale.z
						)}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovL2.geometry}
					/>
					<mesh
						scale-z={getScaleWithOffset(
							table.z,
							LegFL.z,
							1,
							scale.z
						)}
						material={materials.Panel_Beige}
						geometry={nodes.RailL.geometry}
					/>
				</group>
			</group>
			<group name={'Overall Scale'}>
				<group
					name={'coverTopper'}
					visible={cover && topper == 'cover' ? true : false}
					material={materials.Panel_Beige}
					onClick={() => setCover(!cover)}
					scale-x={scale.x}
					scale-z={scale.z}
				>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.CoverR.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.CoverML.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.CoverMR.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.CoverL.geometry}
					/>
					<group name={'twoPieceCover'}>
						<mesh
							material={materials.Panel_Beige}
							geometry={nodes.CoverFillL.geometry}
						/>
						<mesh
							material={materials.Panel_Beige}
							geometry={nodes.CoverFillR.geometry}
						/>
					</group>
					<group name={'threePieceCover'}>
						<mesh
							material={materials.Panel_Beige}
							geometry={nodes.CoverFillC.geometry}
						/>
					</group>
				</group>
				<group
					name={'insetTopper'}
					visible={cover && topper == 'inset' ? true : false}
					scale-x={getScaleWithOffset(
						table.x,
						borderWidth,
						borderScale,
						scale.x
					)}
					scale-z={getScaleWithOffset(
						table.z,
						borderWidth,
						borderScale,
						scale.z
					)}
				>
					<mesh
						visible={table.x * scale.x > 1450 ? false : true}
						material={materials.Panel_Beige}
						geometry={nodes.InsetTopFill.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InsetTopR.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InsetTopL.geometry}
					/>
				</group>

				<mesh
					scale-x={scale.x}
					scale-z={scale.z}
					material={materials.Panel_Beige}
					geometry={nodes.BaseBoard.geometry}
				>
					<meshStandardMaterial color={snap.modelFactors.matColour} />
				</mesh>
			</group>
			<group name={'Corners'}>
				<group
					name={'BackLeftCorner'}
					position-z={getPos(table.z, scale.z)}
					position-x={getPos(table.x, scale.x)}
				>
					<group
						name="topPiecesBR"
						scale-x={borderScale}
						scale-z={borderScale}
						position-x={getEdge(table.x, borderScale)}
						position-z={getEdge(table.z, borderScale)}
					>
						<mesh
							visible={topper == 'inset' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopSetL1.geometry}
						/>
						<mesh
							visible={topper == 'inset' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopSetB3.geometry}
						/>
						<mesh
							visible={topper == 'cover' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopCovB3.geometry}
						/>
						<mesh
							visible={topper == 'cover' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopCovL1.geometry}
						/>
					</group>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.BLLegBlock.geometry}
					/>
					<mesh
						position-z={-getPosOffset(borderWidth / 2, borderScale)}
						position-y={topper == 'cover' ? -9 : 0}
						position-x={-getPosOffset(borderWidth, borderScale)}
						visible={cups}
						material={cupMaterial}
						geometry={nodes.CupBL.geometry}
					/>
					<mesh
						position-x={-getPosOffset(borderWidth / 2, borderScale)}
						position-z={-getPosOffset(borderWidth, borderScale)}
						position-y={topper == 'cover' ? -9 : 0}
						visible={cups}
						material={cupMaterial}
						geometry={nodes.CupLB.geometry}
					/>

					<mesh
						visible={legs == 'Timber' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.LegBL.geometry}
					/>

					<mesh
						visible={legs == 'Steel' ? true : false}
						material={legMaterial}
						geometry={nodes.SteelLegBL.geometry}
					/>
				</group>
				<group
					name={'BackRightCorner'}
					position-z={getPos(table.z, scale.z)}
					position-x={-getPos(table.x, scale.x)}
				>
					<group
						name="topPiecesBR"
						scale-x={borderScale}
						scale-z={borderScale}
						position-x={-getEdge(table.x, borderScale)}
						position-z={getEdge(table.z, borderScale)}
					>
						<mesh
							visible={topper == 'cover' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopCovR3.geometry}
						/>
						<mesh
							visible={topper == 'inset' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopSetR3.geometry}
						/>

						<mesh
							visible={topper == 'inset' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopSetB1.geometry}
						/>
						<mesh
							visible={topper == 'cover' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopCovB1.geometry}
						/>
					</group>

					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.BRLegBlock.geometry}
					/>
					<mesh
						position-z={-getPosOffset(borderWidth / 2, borderScale)}
						position-x={getPosOffset(borderWidth, borderScale)}
						position-y={topper == 'cover' ? -9 : 0}
						visible={cups}
						material={cupMaterial}
						geometry={nodes.CupBR.geometry}
					/>
					<mesh
						position-x={getPosOffset(borderWidth / 2, borderScale)}
						position-z={-getPosOffset(borderWidth, borderScale)}
						position-y={topper == 'cover' ? -9 : 0}
						visible={cups}
						material={cupMaterial}
						geometry={nodes.CupRB.geometry}
					/>
					<mesh
						visible={legs == 'Timber' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.LegBR.geometry}
					/>
					<mesh
						visible={legs == 'Steel' ? true : false}
						material={legMaterial}
						geometry={nodes.SteelLegBR.geometry}
					/>
				</group>
				<group
					name={'FrontLeftCorner'}
					position-z={-getPos(table.z, scale.z)}
					position-x={getPos(table.x, scale.x)}
				>
					{' '}
					<group
						name="topPiecesFL"
						scale-x={borderScale}
						scale-z={borderScale}
						position-x={getEdge(table.x, borderScale)}
						position-z={-getEdge(table.z, borderScale)}
					>
						<mesh
							visible={topper == 'inset' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopSetF1.geometry}
						/>
						<mesh
							visible={topper == 'inset' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopSetL3.geometry}
						/>
						<mesh
							visible={topper == 'cover' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopCovF1.geometry}
						/>
						<mesh
							visible={topper == 'cover' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopCovL3.geometry}
						/>
					</group>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.FLLegBlock.geometry}
					/>
					<mesh
						position-x={-getPosOffset(borderWidth / 2, borderScale)}
						position-z={getPosOffset(borderWidth, borderScale)}
						position-y={topper == 'cover' ? -9 : 0}
						visible={cups}
						material={cupMaterial}
						geometry={nodes.CupLF.geometry}
					/>
					<mesh
						position-z={getPosOffset(borderWidth / 2, borderScale)}
						position-x={-getPosOffset(borderWidth, borderScale)}
						position-y={topper == 'cover' ? -9 : 0}
						visible={cups}
						material={cupMaterial}
						geometry={nodes.CupFL.geometry}
					/>
					<mesh
						visible={legs == 'Timber' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.LegFL.geometry}
					/>
					<mesh
						visible={legs == 'Steel' ? true : false}
						material={legMaterial}
						geometry={nodes.SteelLegFL.geometry}
					/>
				</group>
				<group
					name={'FrontRightCorner'}
					name={'legFR'}
					position-z={-getPos(table.z, scale.z)}
					position-x={-getPos(table.x, scale.x)}
				>
					<group
						name="topPiecesBR"
						scale-x={borderScale}
						scale-z={borderScale}
						position-x={-getEdge(table.x, borderScale)}
						position-z={-getEdge(table.z, borderScale)}
					>
						<mesh
							visible={topper == 'cover' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopCovR1.geometry}
						/>
						<mesh
							visible={topper == 'cover' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopCovF3.geometry}
							material-color={snap.modelFactors.timberColour}
						/>
						<mesh
							visible={topper == 'inset' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopSetF3.geometry}
						/>
						<mesh
							visible={topper == 'inset' ? true : false}
							material={materials.Panel_Beige}
							geometry={nodes.TopSetR1.geometry}
						/>
					</group>

					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.FRLegBlock.geometry}
					/>
					<mesh
						position-z={getPosOffset(borderWidth / 2, borderScale)}
						position-x={getPosOffset(borderWidth, borderScale)}
						position-y={topper == 'cover' ? -9 : 0}
						visible={cups}
						material={cupMaterial}
						geometry={nodes.CupFR.geometry}
					/>
					<mesh
						position-x={getPosOffset(borderWidth / 2, borderScale)}
						position-z={getPosOffset(borderWidth, borderScale)}
						position-y={topper == 'cover' ? -9 : 0}
						visible={cups}
						material={cupMaterial}
						geometry={nodes.CupRF.geometry}
					/>
					<mesh
						visible={legs == 'Timber' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.LegFR.geometry}
					/>
					<mesh
						visible={legs == 'Steel' ? true : false}
						material={legMaterial}
						geometry={nodes.SteelLegFR.geometry}
					/>
				</group>
			</group>
		</group>
	);
}
