/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, useEffect, useState } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { useSnapshot } from 'valtio';
import store from './store';
import { Controls, useControl, withControls } from 'react-three-gui';
import { MeshBasicMaterial } from 'three';
const getNames = (nodes) => {
	// the below function works perfectly except triggers too many re-renders for some reason.
	Object.entries(nodes).map((i) => {
		const name = i[0];
		store.modelFactors[name] = nodes[name].geometry.boundingBox.getSize();
	});
};

export default function Model(props) {
	console.log('component Mount');
	const snap = useSnapshot(store);
	const group = useRef();
	const scale = snap.transforms.scale;
	const { nodes, materials } = useLoader(GLTFLoader, '/SolidTabe.gltf');
	const [cover, setCover] = useState(true);
	const legs = snap.modelFactors.legs;
	const legMaterial = new MeshBasicMaterial({ color: 'black' });
	const topper = snap.modelFactors.topper;

	useEffect(() => {
		// getNames(nodes);

		group.current.castShadow = true;
		group.current.receiveShadow = true;
	}, []);

	useEffect(() => {}, [snap.transforms]);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name={'Front'}>
				<group
					name={'Front Scale'}
					position-z={
						-snap.functions.getPos(
							snap.modelFactors.table.z,
							scale.z
						)
					}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						position-z={
							-snap.functions.getEdge(
								snap.modelFactors.table.z,
								snap.transforms.border
							)
						}
						scale-x={snap.functions.getScale(
							snap.functions.getScale(
								1050 * scale.x,
								1450 * scale.x - 400 * snap.transforms.border
							) * 1450,
							snap.functions.getScale(
								1050 * scale.x,
								1450 * scale.x - 400 * snap.transforms.border
							) *
								1050 *
								snap.transforms.border *
								scale.x
						)}
						scale-z={snap.transforms.border}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetF2.geometry}
					/>
					<mesh
						position-z={
							-snap.functions.getEdge(
								snap.modelFactors.table.z,
								snap.transforms.border
							)
						}
						scale-z={snap.transforms.border}
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovF2.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InnerF.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.RailF.geometry}
					/>
				</group>
			</group>
			<group name={'Back'}>
				<group
					name={'Back Scale'}
					scale-x={scale.x}
					position-z={snap.functions.getPos(
						snap.modelFactors.table.z,
						scale.z
					)}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						position-z={snap.functions.getEdge(
							snap.modelFactors.table.z,
							snap.transforms.border
						)}
						scale-z={snap.transforms.border}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetB2.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						position-z={snap.functions.getEdge(
							snap.modelFactors.table.z,
							snap.transforms.border
						)}
						scale-z={snap.transforms.border}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovB2.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InnerB.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.RailB.geometry}
					/>
				</group>
			</group>
			<group name={'Right'}>
				<group
					name={'Right Scale'}
					scale-z={scale.z}
					position-x={
						-snap.functions.getPos(
							snap.modelFactors.table.x,
							scale.x
						)
					}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						position-x={
							-snap.functions.getEdge(
								snap.modelFactors.table.x,
								snap.transforms.border
							)
						}
						scale-x={snap.transforms.border}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetR2.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InnerR.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						position-x={
							-snap.functions.getEdge(
								snap.modelFactors.table.x,
								snap.transforms.border
							)
						}
						scale-x={snap.transforms.border}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovR2.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.RailR.geometry}
					/>
				</group>
			</group>
			<group name={'Left'}>
				<group
					name={'Left Scale'}
					scale-z={scale.z}
					position-x={snap.functions.getPos(
						snap.modelFactors.table.x,
						scale.x
					)}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						position-x={snap.functions.getEdge(
							snap.modelFactors.table.x,
							snap.transforms.border
						)}
						scale-x={snap.transforms.border}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetL2.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InnerL.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						position-x={snap.functions.getEdge(
							snap.modelFactors.table.x,
							snap.transforms.border
						)}
						scale-x={snap.transforms.border}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovL2.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.RailL.geometry}
					/>
				</group>
			</group>
			<group name={'Overall Scale'} scale-x={scale.x} scale-z={scale.z}>
				<group
					name={'coverTopper'}
					visible={cover && topper == 'cover' ? true : false}
					material={materials.Panel_Beige}
					onClick={() => setCover(!cover)}
				>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.CoverR.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.CoverML.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.CoverMR.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.CoverL.geometry}
					/>
					<group name={'twoPieceCover'}>
						<mesh
							material={materials.Panel_Beige}
							geometry={nodes.CoverFillL.geometry}
						/>
						<mesh
							material={materials.Panel_Beige}
							geometry={nodes.CoverFillR.geometry}
						/>
					</group>
					<group name={'threePieceCover'}>
						<mesh
							material={materials.Panel_Beige}
							geometry={nodes.CoverFillC.geometry}
						/>
					</group>
				</group>
				<group
					name={'insetTopper'}
					visible={cover && topper == 'inset' ? true : false}
				>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InsetTopFill.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InsetTopR.geometry}
					/>
					<mesh
						material={materials.Panel_Beige}
						geometry={nodes.InsetTopL.geometry}
					/>
				</group>

				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.BaseBoard.geometry}
				>
					<meshStandardMaterial color={'hotpink'} />
				</mesh>
			</group>
			<group name={'Legs'}></group>
			<group
				name={'BackLeftCorner'}
				position-z={snap.functions.getPos(
					snap.modelFactors.table.z,
					scale.z
				)}
				position-x={snap.functions.getPos(
					snap.modelFactors.table.x,
					scale.x
				)}
			>
				<group
					name="topPiecesBR"
					scale-x={snap.transforms.border}
					scale-z={snap.transforms.border}
					position-x={snap.functions.getEdge(
						snap.modelFactors.table.x,
						snap.transforms.border
					)}
					position-z={snap.functions.getEdge(
						snap.modelFactors.table.z,
						snap.transforms.border
					)}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetL1.geometry}
					/>
					<mesh
						visible={topper == 'inset' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetB3.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovB3.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovL1.geometry}
					/>
				</group>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.BLLegBlock.geometry}
				/>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.CupBL.geometry}
				/>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.CupLB.geometry}
				/>

				<mesh
					visible={legs == 'Timber' ? true : false}
					material={materials.Panel_Beige}
					geometry={nodes.LegBL.geometry}
				/>

				<mesh
					visible={legs == 'Steel' ? true : false}
					material={legMaterial}
					geometry={nodes.SteelLegBL.geometry}
				/>
			</group>
			<group
				name={'BackRightCorner'}
				position-z={snap.functions.getPos(
					snap.modelFactors.table.z,
					scale.z
				)}
				position-x={
					-snap.functions.getPos(snap.modelFactors.table.x, scale.x)
				}
			>
				<group
					name="topPiecesBR"
					scale-x={snap.transforms.border}
					scale-z={snap.transforms.border}
					position-x={
						-snap.functions.getEdge(
							snap.modelFactors.table.x,
							snap.transforms.border
						)
					}
					position-z={snap.functions.getEdge(
						snap.modelFactors.table.z,
						snap.transforms.border
					)}
				>
					<mesh
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovR3.geometry}
					/>
					<mesh
						visible={topper == 'inset' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetR3.geometry}
					/>

					<mesh
						visible={topper == 'inset' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetB1.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovB1.geometry}
					/>
				</group>

				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.BRLegBlock.geometry}
				/>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.CupBR.geometry}
				/>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.CupRB.geometry}
				/>
				<mesh
					visible={legs == 'Timber' ? true : false}
					material={materials.Panel_Beige}
					geometry={nodes.LegBR.geometry}
				/>
				<mesh
					visible={legs == 'Steel' ? true : false}
					material={legMaterial}
					geometry={nodes.SteelLegBR.geometry}
				/>
			</group>
			<group
				name={'FrontLeftCorner'}
				position-z={
					-snap.functions.getPos(snap.modelFactors.table.z, scale.z)
				}
				position-x={snap.functions.getPos(
					snap.modelFactors.table.x,
					scale.x
				)}
			>
				{' '}
				<group
					name="topPiecesFL"
					scale-x={snap.transforms.border}
					scale-z={snap.transforms.border}
					position-x={snap.functions.getEdge(
						snap.modelFactors.table.x,
						snap.transforms.border
					)}
					position-z={
						-snap.functions.getEdge(
							snap.modelFactors.table.z,
							snap.transforms.border
						)
					}
				>
					<mesh
						visible={topper == 'inset' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetF1.geometry}
					/>
					<mesh
						visible={topper == 'inset' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetL3.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovF1.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovL3.geometry}
					/>
				</group>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.FLLegBlock.geometry}
				/>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.CupLF.geometry}
				/>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.CupFL.geometry}
				/>
				<mesh
					visible={legs == 'Timber' ? true : false}
					material={materials.Panel_Beige}
					geometry={nodes.LegFL.geometry}
				/>
				<mesh
					visible={legs == 'Steel' ? true : false}
					material={legMaterial}
					geometry={nodes.SteelLegFL.geometry}
				/>
			</group>
			<group
				name={'FrontRightCorner'}
				name={'legFR'}
				position-z={
					-snap.functions.getPos(snap.modelFactors.table.z, scale.z)
				}
				position-x={
					-snap.functions.getPos(snap.modelFactors.table.x, scale.x)
				}
			>
				<group
					name="topPiecesBR"
					scale-x={snap.transforms.border}
					scale-z={snap.transforms.border}
					position-x={
						-snap.functions.getEdge(
							snap.modelFactors.table.x,
							snap.transforms.border
						)
					}
					position-z={
						-snap.functions.getEdge(
							snap.modelFactors.table.z,
							snap.transforms.border
						)
					}
				>
					<mesh
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovR1.geometry}
					/>
					<mesh
						visible={topper == 'cover' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopCovF3.geometry}
						material-color={'brown'}
					/>
					<mesh
						visible={topper == 'inset' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetF3.geometry}
					/>
					<mesh
						visible={topper == 'inset' ? true : false}
						material={materials.Panel_Beige}
						geometry={nodes.TopSetR1.geometry}
					/>
				</group>

				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.FRLegBlock.geometry}
				/>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.CupFR.geometry}
				/>
				<mesh
					material={materials.Panel_Beige}
					geometry={nodes.CupRF.geometry}
				/>
				<mesh
					visible={legs == 'Timber' ? true : false}
					material={materials.Panel_Beige}
					geometry={nodes.LegFR.geometry}
				/>
				<mesh
					visible={legs == 'Steel' ? true : false}
					material={legMaterial}
					geometry={nodes.SteelLegFR.geometry}
				/>
			</group>
		</group>
	);
}
